### PR TITLE
update google-u2f

### PR DESCRIPTION
**Pull request by icewind1991**
Updates google-u2f to the latest version from https://github.com/google/u2f-ref-code, re-applying the local changes made (error handling) and adjusting the u2f.sign to have the same interface as the old version.

The update to the library is needed to handle u2f in chrome on android/ios (only tested android myself)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@grantila would you mind taking a look at this pull request? We'd like to use NFC U2F in Nextcloud, ref https://github.com/nextcloud/twofactor_u2f/issues/96

Thanks a lot!

**Comment by ChristophWurst** [comment]
@grantila ping

**Comment by grantila** [comment]
Sorry for the delay, it's merged now. They obviously deleted the `disconnect` method which according to #1 may be problematic.. We'll just see how this plays out.
Published in 0.3.0

**Comment by ChristophWurst** [comment]
@grantila no worries. Thanks for merging this PR :rocket:

**Pull request merged**
